
if O2SCL_LIBTORCH
LIBTORCH_VAR = set_libtorch.h
else
LIBTORCH_VAR = 
endif

# ------------------------------------------------------------
# Install headers
# ------------------------------------------------------------

am__pkginclude_HEADERS_DIST = set_libtorch.h

pkginclude_HEADERS = $(LIBTORCH_VAR)

