---
name: openSUSE TW i386 minimal install

on:
  push:
    branches: [ "main", "rc" ]
  pull_request:
    branches: [ "main", "rc" ]

jobs:
  tests-opensuse-tumbleweed-i386:

    runs-on: ubuntu-22.04
    container:
      image: opensuse/tumbleweed
      options: --platform "linux/386"

    steps:

#    - name: Git checkout
#      uses: actions/checkout@v1

    - name: Download release
      uses: robinraju/release-downloader@v1
      with:
        repository: 'awsteiner/o2scl'
        tag: 'v0.929.2'
        fileName: 'o2scl-0.929.2.tar.gz'

    - name: Extract release and reorganize
      run: |
           tar xvzf o2scl-0.929.2.tar.gz
           mv o2scl-0.929/* .
           rmdir o2scl-0.929

    # (Cache actions do not work for 32-bit containers on 64-bit runners.)

    - name: Install dependencies
      run: zypper --non-interactive install --no-recommends ccache gawk gcc-c++ hdf5-devel libtool make pkgconfig python3 readline-devel boost-devel "pkgconfig(armadillo)" "pkgconfig(eigen3)" "pkgconfig(fftw3)" "pkgconfig(gsl)" "pkgconfig(mpfr)" "pkgconfig(ncurses)"

#    - name: Set up autotools scripts
#      run:
#        ./autogen.sh

    - name: Configure
      run: |
        cd ${GITHUB_WORKSPACE}
        export CC='ccache gcc'
        export CXX='ccache g++'
        export CXXFLAGS+="-DO2SCL_PLAIN_HDF5_HEADER -DO2SCL_OPENSUSE -DO2SCL_OPENSUSE_I386"
        export LDFLAGS+="-lgomp"
        export CCACHE_DIR=~/.ccache
        ./configure --build=i386-suse-linux --enable-shared --disable-static --enable-armadillo --enable-eigen --enable-fftw --enable-openmp --enable-ncurses --disable-pugixml --disable-python

    - name: Install
      run: |
        cd ${GITHUB_WORKSPACE}
        make VERBOSE=1 sinstall -j4 -O
        make VERBOSE=1 -C data install-data

    - name: Check
      run: |
        cd ${GITHUB_WORKSPACE}
        make VERBOSE=1 o2scl-test -j4 -O
