name: test build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: sudo apt-get -y install g++ make libgsl-dev curl tar gzip libhdf5-dev libreadline-dev libboost-all-dev git libz-dev libsz2 libquadmath0
    - name: reconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: sudo make install
    - name: make check
      run: make check
    - name: acol
      run: acol -v
